zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

management.endpoints.web.exposure.include: health,info,prometheus
management.metrics.export.prometheus.enabled: true
spring.sleuth.sampler.probability: 1
