{
 "title": "Spring PetClinic Microservices",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": "CUSTOMERS-SERVICE, API-GATEWAY, VETS-SERVICE, VISITS-SERVICE"
   },
   {
    "name": "jvmMemory",
    "label": "JVM Memory",
    "query": "PS Eden Space, PS Old Gen, PS Survivor Space, Code Cache, Compressed Class Space, Metaspace"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_cpu_usage{service=\"$service\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\", exported_id=\"$jvmMemory\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{service=\"$service\"}"
    },
    {
     "expr": "system_load_average_1m{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Eden",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service=\"$service\", exported_id=\"$jvmMemory\"}"
    },
    {
     "expr": "jvm_memory_committed_bytes{service=\"$service\", exported_id=\"$jvmMemory\"}"
    },
    {
     "expr": "jvm_memory_max_bytes{service=\"$service\", exported_id=\"$jvmMemory\"}"
    }
   ]
  },
  {
   "title": "JDBC Connection Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jdbc_connections_active{service=\"$service\"}"
    },
    {
     "expr": "jdbc_connections_max{service=\"$service\"}"
    },
    {
     "expr": "jdbc_connections_min{service=\"$service\"}"
    }
   ]
  }
 ]
}